package application.applicationLayer;

public class UC2 {

	public void selbstTesten(boolean selbstTesten) {
		return;
	}

	public void wissensstandszeigerErhoehen(Kategorie kategorie) {
		return;
	}

	public void antwortPruefen(int antwortNummer) {
		return;
	}

	public void kategorieSetzen(Kategorie kategorie) {
		// generated by Together
		Kategorie b = null;
		// Message #1.1 to b:Kategorie
		b.getRandomFrage();
	}

}
