package application.applicationLayer;

public class UseCaseController2 {
	
	private int aktuelleKategorie;
	private Frage aktuelleFrage;
	private Spieler testenderSpieler;
	private Spieler getesteterSpieler;
	private ModelFront modelFront;

	
	

	public UseCaseController2(ModelFront modelFront) {
		this.modelFront = modelFront;
	}
	
	public void selbstTesten(boolean selbstTesten) {
		return;
	}

	public void wissensstandszeigerErhoehen(Kategorie kategorie) {
		return;
	}

	public void antwortPruefen(int antwortNummer) {
		if(antwortNummer == aktuelleFrage.getRichtigeAntwortNummer()){
			int wissensstandszeiger = getesteterSpieler.getWissensstandszeiger().getWissensstandVonKategorie(aktuelleKategorie);
		}
		return;
	}

	public void kategorieSetzen(Kategorie kategorie) {
		// generated by Together
		Kategorie b = null;
		// Message #1.1 to b:Kategorie
		b.getRandomFrage();
	}

}
